[project]
name = "comfystereo"
description = "Two simple nodes for stereoscopic image generation. Nodes: Stereo Image Node - a basic port from the Automatic1111 stereo script in thygate/stable-diffusion-webui-depthmap-script, LazyStereo - a na√Øve stereo image generator"
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["torch", "numpy", "Pillow", "opencv-python"]

[project.urls]
Repository = "https://github.com/Dobidop/ComfyStereo"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "dobidop"
DisplayName = "ComfyStereo"
Icon = ""
